### ISSUE TITLE
Valid .zip files

### ISSUE THREAD

**Issue by Katsivelisp** [freme-project/e-Publishing#20]
Hi,

I've been trying to use the e-publishing service with a sample .zip of mine and I've been getting the same Error 400: "Something went wrong with the provided Zip file. Make sure you are providing a valid Zip file".

How can I track down what's wrong with my file? Any hints for future reference? Maybe we could also add some guidelines to the documentation.
[GWPP_epub.zip](https://github.com/freme-project/e-Publishing/files/315633/GWPP_epub.zip)

**Comment by jnehring** [comment]
@ArneBinder please take a look at this. This is the first time e-publishing is used after the architecture update.

**Comment by pheyvaer** [comment]
For debugging purposes, could you provide all parameters, together with the `curl` command?

**Comment by Katsivelisp** [comment]
Hi @pheyvaer,

sure, this is the curl:
`curl --form "htmlZip=@GWPP_epub.zip" --form metadata='{"titles":["Polyomavirus and Papillomavirus" ], "creators":[    {        "firstName": "Giannis",        "lastName": "Stoitsis",        "roles":["author"]    } ], "contributors":[    {        "firstName": "Panagis",        "lastName": "Katsivelis",        "roles":["illustrator"]    },    {        "firstName": "Panagis",        "lastName": "Stoitsis",        "roles":["illustrator"]    } ], "subjects":[    "water pathogens",    "viruses" ], "language":"en", "descriptions":["This is the story about a water pathogen."], "identifier":{    "value":"urn:1235-568-2235" }, "tableOfContents":[    {       "title":"Chapter 1",       "resource":"Chapter.html"    } ]}' http://api-dev.freme-project.eu/current/e-publishing/html > book.epub`

Ι just noticed that I didn't set the `resource` attribute correctly under `tableOfContents` in the metadata. Now it seems to be working.

**Comment by Katsivelisp** [comment]
Is it possible to describe such kind of dependencies in the documentation? I think it would be very useful.

**Comment by pheyvaer** [comment]
Do you mean the explanation about `resource`?

This is what's present at the doc currently:

> tableOfContents (optional) - it is an ordered list of the chapters/sections in the EPUB. For each you provide the title and the corresponding HTML file (= **resource**). If no tableOfContents is provided, the service will do a best effort at creating one. However, when no (x)html file is found in the root of the zip, the service will return an invalid EPUB.

If not clear enough, we can update it of course.

**Comment by Katsivelisp** [comment]
Nope, my bad. It is clear enough. Just figured that since it was optional, it wouldn't break the process. :)
