### ISSUE TITLE
Call on api-dev returns .zip file without EPUB file

### ISSUE THREAD

**Issue by Katsivelisp** [freme-project/e-Publishing#22]
Hi,

I am running test calls on api-dev with the provided .zip file and call:
`curl --form "htmlZip=@epub_material.zip" --form metadata='{"titles":["Polyomavirus and Papillomavirus" ], "creators":[    {        "firstName": "Giannis",        "lastName": "Stoitsis",        "roles":["author"]    } ], "contributors":[    {        "firstName": "Panagis",        "lastName": "Katsivelis",        "roles":["illustrator"]    },    {        "firstName": "Panagis",        "lastName": "Stoitsis",        "roles":["illustrator"]    } ], "subjects":[    "water pathogens",    "viruses" ], "language":"en", "descriptions":["This is the story about a water pathogen."], "identifier":{    "value":"urn:1235-568-2235" }, "tableOfContents":[    {       "title":"Chapter 1",       "resource":"Chapter.html"    } ]}' http://api-dev.freme-project.eu/current/e-publishing/html > book`
[epub_material.zip](https://github.com/freme-project/e-Publishing/files/327276/epub_material.zip)

The service returns a .zip file with a specific file structure (META-INF, OEBPS, mimetype), but no generated EPUB file is included. Am I missing something? Do I have to work on the format of my HTML document?

**Comment by pheyvaer** [comment]
What is the difference with the call you did in issue #20?

EDIT: additionally, an EPUB is a zip, and the actual content (HTML) can be found in the folder OEBPS. So if you change the `> book` at the end of your command to `> book.epub` you get an EPUB.

**Comment by Katsivelisp** [comment]
The attached text file is different, as in more recent. Also, there is no error this time, I'm just trying to figure out the response.

Okay, I get it now, thanks. However, when I open book.epub with an EPUB reader, I get the following error:
`Empty file: OEBPS/content.opf`

Plus, when I try to validate my .epub file on http://validator.idpf.org/, I get the following errors:
    -   Error while parsing file 'Premature end of file.'.
    -   There was an error when parsing the EPUB version: Version not found.

Do these help?

**Comment by pheyvaer** [comment]
Could you send me the file (via email or attach it here) you got from the service? so I can have a look at it.

**Comment by Katsivelisp** [comment]
Sure, this is it:
[response.zip](https://github.com/freme-project/e-Publishing/files/327404/response.zip)

I can't upload it with an .epub extension on GitHub, so please change it from .zip to .epub.

**Comment by pheyvaer** [comment]
After some debugging I found out that not all URLs in the file URL encoded, i.e., `&` is used while actually `&amp;` should be used. EPUB uses `xhtml` which is based on `xml` hence more strict when using characters like this.

**Comment by Katsivelisp** [comment]
So, ideally, we want our Drupal website to be fully in XHTML, right?

**Comment by pheyvaer** [comment]
That would be the ideal case. You can convert `html` to `xhtml`, but that might not always give the wanted result. I don't know if it is possible to provide `xhtml` directly from Drupal?

**Comment by Katsivelisp** [comment]
No, it isn't. I'm searching for an easy alternative way though (edit: outside of Drupal that is).

**Comment by Katsivelisp** [comment]
Hi again,

I tried to make all necessary parts of the website as XHTML-compliant as possible. So now I want to run the e-publishing service on this: [http://waterpathogens.agroknow.gr/print/110](http://waterpathogens.agroknow.gr/print/110), which does fairly well on [W3C's XHTML validator](https://validator.w3.org). I also fixed all instances of bad URL-encoded characters (such as "&").

So if I download the above website, run the cURL command and retrieve the EPUB file, my EPUB reader shows the same error:
`Empty file: OEBPS/content.opf`

Any ideas?

**Comment by pheyvaer** [comment]
Can you attach the `html` file?

**Comment by Katsivelisp** [comment]
Here it is.
[epub_material.zip](https://github.com/freme-project/e-Publishing/files/336713/epub_material.zip)

**Comment by pheyvaer** [comment]
I see that at line 385 there is still an `&` that is not encoded, before version: `<a href="http://www.cancer.gov/Common/PopUps/popDefinition.aspx?id=CDR0000748141&version=Patient&language=English">CDC</a>`.

This might make things clearer http://stackoverflow.com/questions/275150/xhtml-and-ampersand-encoding

**Comment by Katsivelisp** [comment]
Even if I remove that link entirely, the same error is produced.

**Comment by pheyvaer** [comment]
Did you remove all the links where this was the case? The one I gave was just one example.

**Comment by Katsivelisp** [comment]
Hi,

you were right! There were some links produced during the page post-processing. I removed the ampersands there as well and it now works! My EPUB opens etc. Thank you very much! :)
