### ISSUE TITLE
Internal table of contents

### ISSUE THREAD

**Issue by Katsivelisp** [freme-project/e-Publishing#23]
Hello everyone,

this is not really an issue, but a question: Is there a way for the e-publishing service to generate a table of contents for the internal parts of an .xhtml document? For example, a table of contents of all header tags (h1, h2 etc).

**Comment by pheyvaer** [comment]
You can do it manually in the json you provide with the call. However, it is not possible to do this automatically.

**Comment by Katsivelisp** [comment]
Hi @pheyvaer,

can you give me an example? I thought that the "table of contents" part of the call only accepted two fields: the title and the filename of the resource. In any case, I'm fine with generating this manually.

**Comment by pheyvaer** [comment]
The filename can actually also contain an html id. E.g., if you have the file `index.html` and a `<div id="first-section">` in that file. You can refer to that specific `div` using `index.html#first-section`.

**Comment by Katsivelisp** [comment]
Thanks for the response @pheyvaer !

I already tried what you proposed and it doesn't seem to work. For example, for the following zip, I run these two cURLs:

`curl --form "htmlZip=@epub_material.zip" --form metadata='{"titles":["Chapter 1" ], "creators":[    {        "firstName": "Giannis",        "lastName": "Stoitsis",        "roles":["author"]    } ], "contributors":[    {        "firstName": "Panagis",        "lastName": "Katsivelis",        "roles":["illustrator"]    },    {        "firstName": "Panagis",        "lastName": "Stoitsis",        "roles":["illustrator"]    } ], "subjects":[    "water pathogens",    "viruses" ], "language":"en", "descriptions":["This is the story about a water pathogen."], "identifier":{    "value":"urn:1235-568-2235" }, "tableOfContents":[    {       "title":"Polyomavirus",       "resource":"Chapter.html"    } ]}' http://api-dev.freme-project.eu/current/e-publishing/html > chapter.epub`

`curl --form "htmlZip=@epub_material.zip" --form metadata='{"titles":["Chapter 1" ], "creators":[    {        "firstName": "Giannis",        "lastName": "Stoitsis",        "roles":["author"]    } ], "contributors":[    {        "firstName": "Panagis",        "lastName": "Katsivelis",        "roles":["illustrator"]    },    {        "firstName": "Panagis",        "lastName": "Stoitsis",        "roles":["illustrator"]    } ], "subjects":[    "water pathogens",    "viruses" ], "language":"en", "descriptions":["This is the story about a water pathogen."], "identifier":{    "value":"urn:1235-568-2235" }, "tableOfContents":[    {       "title":"Polyomavirus",       "resource":"Chapter.html#toc1"    } ]}' http://api-dev.freme-project.eu/current/e-publishing/html > chapter.epub`

Only the first one produces an EPUB.

[epub_material.zip](https://github.com/freme-project/e-Publishing/files/471646/epub_material.zip)

**Comment by pheyvaer** [comment]
I think I know why it goes wrong. I'll have a look at it.

**Comment by Katsivelisp** [comment]
Hi @pheyvaer,

are there any updates to this?

**Comment by pheyvaer** [comment]
I think I've fixed it, but I can't test it yet, see [this issue](https://github.com/freme-project/freme-packages/issues/21).

**Comment by Katsivelisp** [comment]
Hi @pheyvaer ,

until your fixes are compiled, can I at least remove the produced table of contents from the generated EPUB? When I remove the parameter "tableOfContents" from the call, a table is still placed at the bottom of the EPUB.

**Comment by pheyvaer** [comment]
What do you mean with 'at the bottom of the EPUB'?

**Comment by Katsivelisp** [comment]
The generated EPUB file contains the content from the .xhtml document + a default table of contents which only contains the name of the Chapter file.

**Comment by pheyvaer** [comment]
Yes, but table of contents appears in multiple files, in which on do you want it removed?

**Comment by Katsivelisp** [comment]
We only send one .xhtml file and the service returns one EPUB file with a table of contents that features just one record (for this one .xhtml file). In such a case, it would be better not to generate a table of contents at all.

**Comment by pheyvaer** [comment]
OK, I see, but an EPUB needs to have an ToC, you can't leave it out.

**Comment by pheyvaer** [comment]
hi @Katsivelisp so I've fixed it. Could you try it and let me know?

**Comment by Katsivelisp** [comment]
Hi @pheyvaer, I'm sorry for the late answer. Yes, it works great, thank you very much!

**Comment by Katsivelisp** [comment]
Hello @pheyvaer ,

just a follow-up question to this. Is there a way to define a tree structure for a table of contents? So, let's say headings and sub-headings of a document passed to the call?

**Comment by pheyvaer** [comment]
Hi,

You can test with the following code.

```
"tableOfContents":[ { "title":"Polyomavirus", "resource":"Chapter.html", "subsections": [{"title": "Subsection A", "resource":"test.html"}] } ]
```

So for each `section` in the `tableOfContents` you can define the `subsections`. Please let me know if this is working for you or not.

**Comment by Katsivelisp** [comment]
Hi @pheyvaer,

I tried what you proposed, but I get a Server Error (500). My table of contents is as following:

```
"tableOfContents": [{
        "title": "Section",
        "resource": "Chapter.html#toc1",
        "subsections": [{
            "title": "Subsection A",
            "resource": "Chapter.html#toc2"
        }]
    }]
```

**Comment by pheyvaer** [comment]
I'll have a look at this, after we installed completed the local FREME installation.

**Comment by pheyvaer** [comment]
@Katsivelisp a quick update: I've got it working locally, but have some issues to get it on the server.

**Comment by pheyvaer** [comment]
@Katsivelisp it works on the server now. Can you check?

**Comment by Katsivelisp** [comment]
@pheyvaer, it works great I believe! Thank you very much for your work!
